version: "3.8"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8007
    volumes:
      - .:/code
    ports:
      - 8007:8007
    depends_on:
      - db
    environment:
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:

  